name: Publish client conformance report

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  fetch-results:
    name: Fetch ${{ matrix.name }} results
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Don't stop if one client results download fails
      matrix:
        include:
          - name: python-tuf
            repo: theupdateframework/python-tuf
            workflow: conformance.yml
          - name: tuf-js
            repo: theupdateframework/tuf-js
            workflow: conformance.yml
          - name: sigstore-java
            repo: sigstore/sigstore-java
            workflow: tuf-conformance.yml
          - name: sigstore-ruby
            repo: sigstore/sigstore-ruby
            workflow: ci.yml


    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
        with:
          # A token is required to read other repos' artifacts. This token is a fine grained token
          # with read-only "public repositories" access only. It is set to expire in 1 year
          # (maximum accepted by OpenSSF)
          github_token: ${{ secrets.READ_ONLY_TOKEN }}
          repo: ${{ matrix.repo }}
          workflow: ${{ matrix.workflow }}
          branch: main
          name: tuf-conformance-results
          workflow_conclusion: success
          path: ./results/
        continue-on-error: true

      - name: Rename artifact for aggregation
        run: |
          if [ -f "./results/tuf-conformance-report.json" ]; then
            mv ./results/tuf-conformance-report.json "./results/${{ matrix.name }}.json"
          else
            # create empty file so report generator can still include the client as "not found"
            mkdir ./results
            echo "{}" > "./results/${{ matrix.name }}.json"
          fi

      - name: Upload ${{ matrix.name }} results
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ matrix.name }}-result
          path: ./results/${{ matrix.name }}.json

  build-report:
    name: Build client conformance report
    runs-on: ubuntu-latest
    needs: [fetch-results]
    if: always()

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Download all individual results
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          pattern: '*-result'
          path: ./results

      - name: Generate report
        run: |
          python .github/scripts/generate_client_report.py \
            --reports-dir ./results \
            --output results/index.html

      - name: Upload report for Pages
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: results/

  deploy-pages:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-report
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5